### PR TITLE
Remove my Xen-4.4 RPM, use the Xen4CentOS one.

### PR DESCRIPTION
**Pull request by djs55**
We're still using my OCaml-4.01 rpm on xenbits though.

Signed-off-by: David Scott <dave.scott@eu.citrix.com>

### CODE REVIEW

**Comment by djs55** [comment]
This failed because it picked up the ocaml-findlib from centos which depends on ocaml 3. I'll add find lib and opam to my ocaml repo since these are really "core" ocaml tools.

**Comment by djs55** [comment]
OK, this is annoying: it looks like the 'cbs.centos.org' URLs are unreliable:
```
ERROR: Exception(SRPMS/ocaml-comparelib-109.60.00-1.el6.src.rpm) Config(epel-6-x86_64) 0 minutes 7 seconds
ERROR: http://cbs.centos.org/repos/virt6-testing/x86_64/os/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
0:ccache-3.1.6-2.el6.x86_64
```
where the URL was working earlier and it works for me from a different host.

**Comment by djs55** [comment]
I have no idea why it's failing now -- it built ok for me on my test box. @BobBall any ideas?

**Comment by BobBall** [comment]
I didn't think mock expanded $variables, thus the repo might not be reachable?

**Comment by djs55** [comment]
ooh ok, will take a look

On Thu, Jan 29, 2015 at 11:08 AM, Bob Ball <notifications@github.com> wrote:

> I didn't think mock expanded $variables, thus the repo might not be
> reachable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xenserver/buildroot/pull/599#issuecomment-72007568>.
>



-- 
Dave Scott

**Comment by djs55** [comment]
ocplib-endian failure

**Comment by djs55** [comment]
@xen-git retest this please

**Comment by djs55** [comment]
ocplib-endian again

**Comment by djs55** [comment]
@xen-git retest this please

**Pull request merged**
